### ISSUE TITLE
專案命名

### ISSUE THREAD

**Issue by RexYuan** [communityNTNU/WatchNTNU#1]
> This is an GitHub issue about the naming issue of the issue board we're planning on.

直接叫 issueBoard 實在... 不太喜歡。

這個清單應該集合所有可考慮的名字，並依我們其他的同樣風格做為標準（___ NTNU）：
1. Solving NTNU
2. Solve NTNU
3. [Heimdall](http://marvel-movies.wikia.com/wiki/Heimdall)/[Heimdallr](https://en.wikipedia.org/wiki/Heimdallr) NTNU
4. Watcher NTNU
5. Fix NTNU
6. Bulletin NTNU
7. Report NTNU
8. Notice NTNU
9. Watch NTNU

...

**Comment by wildskyf** [comment]
應該要原形動詞（跟 survive 一樣）
我覺得 solveNTNU 不錯XD
不過我們已經有一個 s 了

**Comment by wildskyf** [comment]
或是用公告板之類的想法？

**Comment by RexYuan** [comment]
我覺得在意識上來說 應該有個「We're watching you.」的感覺 所以才想到 Heimdall/Heimdallr （Yeah, I'm a fucking nerd）不過應該不會有很多人懂...

![](http://s3.amazonaws.com/digitaltrends-uploads-prod/2014/11/Thor-Heimdall.jpg)

我也是一開始想到 Solve 但後來想到我們其實只是一個監督者的角色 公告版滿不錯的 我會加上 Report（可能跟新聞混淆）, Bullentin（可能跟討論板混淆）, Notice

**Comment by RexYuan** [comment]
新增 Watch NTNU

**Comment by wildskyf** [comment]
watchNTNU 不錯呀～

**Comment by RexYuan** [comment]
Renamed to Watch NTNU
